### PR TITLE
5oappy/feature/integration testing schedulerv2

### PR DESCRIPTION
**Pull request by 5oappy**
## Describe your changes
note: merged lindas changes into this branch before Linda's was merged into main so there may be some inconsistencies that will need to be manually resolved.
real changes begin at 1ecbfe08a58d8baad160e5cb47070d7895248ec4.

I know its a mess but it works!!

The scheduler works correctly according to this control flow:

1) api is called and..
2) optimiser instance is created
3) optimiser invokes calculator instance
4) calculator instance retrieves all required data
5) optimiser calls calculator methods to assign varaibles
6) minizinc instance created with the model string
7) variables are assigned to minizinc model string
8) minizinc solves the model
9) minizinc returns the posssible assignments
10) possible assignments are returned to api
11) api invokes save result to persist possible assignments to database and setting relevant flags.
12) api returns {"message": "Optimisation completed successfully", "result": <minizinc result string>}

Further info on calculator:

- The scheduler will optimise all recently created shifts marked via the status flag being set to SUBMITTED (as in just submitted).
- The scheduler will allow for users to be assigned to multiple shifts provided their skills align.
- The scheduler will allow for clashes in scheduling.
- The actual saving of volunteer shift will check for clashes.
- `unavailability_record` is created for each successful user assigned and saved to the shift (each `shift_request_volunteer` entry added to the db). This prevents the optimiser from thinking user is available for subsequent optimisations.

pictures:
before calling optimiser:
Screenshot 2024-10-06 at 11 13 05 PM

after calling optimiser:
Screenshot 2024-10-06 at 11 13 20 PM

logs:
Screenshot 2024-10-06 at 11 56 37 PM

Screenshot 2024-10-07 at 12 00 01 AM
Screenshot 2024-10-07 at 12 01 48 AM
Screenshot 2024-10-06 at 10 16 14 PM

note: the second phone has duplicate shifts because of a bug that allowed 2 shifts to be posted via post man at the same time and got persisted when the optimiser was not set up to handle clashes yet. 

signed:
Steven, Hafizh, Linda. 

## Issue ticket number and link

[FIR-4](https://fireapp-emergiq-2024.atlassian.net/browse/FIR-4) [FIR-108](https://fireapp-emergiq-2024.atlassian.net/browse/FIR-108)

### CODE REVIEW

**Review by BenMMcLean — DISMISSED** [review]
This looks great. There are probably a couple things I could comment on, but none are egregious enough for me to hold up this so close to deadline. Might be worth just documenting them somewhere for future

**Comment by 5oappy** [comment]
im documenting rn ben :)

**Comment by 5oappy** [comment]
sorry ben I forgot to push one commit.

**Review by BenMMcLean — APPROVED** [review]

**Comment by ethantr** [comment]
Awesome work

**Pull request merged**
